# Generated by Django 4.2.7 on 2023-11-08 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuadrilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Cuadrilla",
                "verbose_name_plural": "Cuadrillas",
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("paterno", models.CharField(max_length=50, verbose_name="Paterno")),
                ("materno", models.CharField(max_length=50, verbose_name="Materno")),
                ("telefono", models.CharField(max_length=10, verbose_name="Telefono")),
                ("puesto", models.CharField(max_length=50, verbose_name="Puesto")),
                (
                    "cuadri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="webLimpieza.cuadrilla",
                        verbose_name="Cuadrilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
            },
        ),
    ]
