# Generated by Django 4.2.7 on 2023-11-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webLimpieza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cod_postal', models.CharField(max_length=5, verbose_name='Codigo_Postal')),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuadriM',
            field=models.ManyToManyField(related_name='cuadrilla', to='webLimpieza.cuadrilla', verbose_name='Cuadrilla'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuadri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='webLimpieza.cuadrilla', verbose_name='ID_Cuadrilla'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='webLimpieza.empleado', verbose_name='ID_Empleado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Foto')),
                ('detalle', models.TextField(max_length=100, verbose_name='Detalle')),
                ('cuadri', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='webLimpieza.cuadrilla', verbose_name='ID_Cuadrilla')),
                ('id_colonia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='webLimpieza.colonia', verbose_name='ID_Colonia')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
