# Generated by Django 4.2.7 on 2023-11-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webLimpieza', '0002_colonia_empleado_cuadrim_alter_empleado_cuadri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cuadriM',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='foto',
            field=models.ImageField(default='null', upload_to='fotos/', verbose_name='Foto'),
        ),
    ]
