# Generated by Django 4.2.7 on 2023-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webLimpieza', '0003_remove_empleado_cuadrim_alter_actividad_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='foto',
            field=models.ImageField(default='null', upload_to='img/', verbose_name='Foto'),
        ),
    ]
