# Generated by Django 4.2.7 on 2023-11-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webLimpieza', '0005_alter_actividad_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('jefe_cuadrilla', 'Jefe de cuadrilla'), ('empleado', 'Empleado')], max_length=50, verbose_name='Puesto'),
        ),
    ]
