# Generated by Django 4.2.7 on 2023-11-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webLimpieza', '0006_alter_empleado_puesto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
